SEGREGACIONES_PROFUNDIDAD_TRES_TABS = ['DU.04', 'DU.05', 'DU.06', 'RS.02', 'IP.01', 'IP.03', 'EC.01', 'SU.07', 'SU.08',
                                       'SU.09', 'SU.10', 'SU.11', 'SU.12', 'RH.01', 'RH.03', 'RH.04', 'RH.05',
                                       'RH.02.1', ]
TABS_SUMATORIA_SOLO_VERTICAL_TABS = []
TABS_PROMEDIO_TABS = ['SU.06', 'SU.07', 'SU.08', 'SU.09', 'SU.10', 'SU.11', 'SU.12', 'IL.03', 'IL.04']
TABS = SEGREGACIONES_PROFUNDIDAD_TRES_TABS + TABS_SUMATORIA_SOLO_VERTICAL_TABS + TABS_PROMEDIO_TABS

SEGREGACIONES_PROFUNDIDAD_TRES = ['PA.01', 'PA.03', 'PA.04', 'PA.05', 'PA.07', 'PA.10', 'PA.11', 'RA.01',
                                  'RA.02', 'RA.03', 'RA.04', 'RA.05', 'RA.06', 'RA.07',
                                  'SU.13', 'RS.07', ]
TABLAS_LINEAL = ['CES.01', 'CES.02', 'CES.03', 'RH.02', 'RH.06']
TABLAS_PROMEDIO = ['CES.04', 'CES.05', 'CES.06', 'CES.07', 'SU.01', 'SU.02', 'SU.03', 'SU.04', 'SU.05', 'IL.01',
                   'IL.02']
TABA_SUMATORIA_SOLO_VERTICAL = ['OA.01', 'OA.02', 'OA.03', 'IP.04', 'RS.03', 'RS.04', 'RS.05', 'IP.02',
                                'IP.04', 'PU.01', 'PU.02', 'PU.03', 'PU.04', ]
TABLA_SIN_SUMATORIA = ['CES.04', 'CES.05', 'OA.04', ]
TABLA_PORCENTUAL = []
# TABLA_PORCENTUAL = ['OA.01', 'OA.02', 'OA.03', 'OA.04', 'PA.02', ]

EXEPCIONES_DECIMALES = ['CES.01', 'CES.02', 'CES.03', 'CES.04', 'CES.05', 'CES.06']

SUNBURTS = ['IP.01']
NO_GRAFICAS = ['PA.01', 'PA.04', 'PA.05', 'PA.06', 'PA.07', 'PA.08', 'PA.10', 'PA.11',
               'RA.01', 'RA.01', 'RA.02', 'RA.03', 'RA.04', 'RA.05', 'RA.06', 'RA.07',
               'RH.09', 'IP.05', 'RS.01', 'EC.03', 'EC.04', 'DU.06']
PIE = ['PA.03', 'EC.01', 'EC.02', ]
NO_BARS = []
TOTALES_BARS = ['CES.02', 'CES.04', 'DU.04', 'DU.05', 'RH.03', 'RH.04', 'RH.05', 'RH.06',]
PROMEDIOS_BARS = ['CES.05', 'CES.06', 'CES.07', 'SU.06', 'SU.07', 'SU.08', 'SU.09', 'SU.10', 'SU.11', 'SU.12', 'IL.01',
                  'IL.02', ]

LABELS = {
    'CES.01': '',
    'CES.02': '',
    'CES.03': '',
    'CES.04': '',
    'CES.05': '',
    'CES.06': '',
    'CES.07': '',
    'OA.01': '',
    'OA.02': '',
    'OA.03': '',
    'OA.04': '',
    'DU.01': '',
    'DU.02': '',
    'DU.03': '',
    'DU.04': '',
    'DU.05': '',
    'DU.06': '',
    'DU.07': '',
    'PA.01': '',
    'PA.02': '',
    'PA.03': '',
    'PA.04': '',
    'PA.05': '',
    'PA.06': '',
    'PA.07': '',
    'PA.08': '',
    'PA.09': '',
    'PA.10': '',
    'RA.01': '',
    'SU.01': '',
    'SU.02': '',
    'SU.07': '',
    'SU.08': '',
    'SU.09': '',
    'SU.13': '',
    'RH.01': '',
    'RH.02': '',
    'RH.02.1': '',
    'RH.03': '',
    'RH.04': '',
    'RH.05': '',
    'RH.06': '',
    'RH.07': '',
    'RH.09': '',
    'IP.01': '',
    'IP.02': '',
    'IP.03': '',
    'IP.04': '',
    'IP.05': '',
    'ERS.01': '',
    'ERS.02': '',
    'ERS.03': '',
    'ERS.04': '',
    'RS.01': '',
    'RS.02': '',
    'RS.03': '',
    'RS.04': '',
    'RS.05': '',
    'RS.06': '',
    'RS.07': '',
    'IL.01': '',
    'IL.02': '',
    'IL.03': '',
    'PU.01': '',
    'PU.02': '',
    'PU.03': '',
}
# LABELS = {
#     'CES.01': '',
#     'CES.02': '',
#     'CES.03': '',
#     'CES.04': 'Tasa de analfabetismo (Población de 15 años y más) según sexo',
#     'CES.05': 'Tasa bruta de matrícula nivel superior (Población 18-24 años) según sexo',
#     'CES.06': 'Índice de paridad de género en tasa bruta de matricula según nivel educativo medio y superior',
#     'CES.07': 'Desagregaciones',
#     'OA.01': 'Distribución de la oferta académica',
#     'OA.02': 'Recinto',
#     'OA.03': 'Recinto',
#     'OA.04': 'Programa de grado',
#     'DU.01': 'Recinto',
#     'DU.02': 'Recinto',
#     'DU.03': 'Recinto',
#     'DU.04': 'Programas',
#     'DU.05': 'Programas',
#     'DU.06': 'País',
#     'DU.07': 'Posición de instituciones',
#     'PA.01': 'Programas',
#     'PA.02': 'Programas',
#     'PA.03': 'Programas',
#     'PA.04': 'Programas',
#     'PA.05': 'Programas',
#     'PA.06': 'Programas',
#     'PA.07': 'Programas',
#     'PA.08': 'Recinto',
#     'PA.09': 'Universidad',
#     'PA.10': 'Programas',
#     'RA.01': 'Programas',
#     'SU.01': 'Categoría',
#     'SU.02': 'Recinto',
#     'SU.07': 'Categoría',
#     'SU.08': 'Categoría',
#     'SU.09': 'Año',
#     'SU.13': 'Escuela',
#     'RH.01': 'Categoría',
#     'RH.02': 'Categoría',
#     'RH.02.1': 'Categoría',
#     'RH.03': 'Nivel académico',
#     'RH.04': 'Categoría',
#     'RH.05': 'Categoría',
#     'RH.06': 'Categoría',
#     'RH.07': 'Categoría',
#     'RH.09': 'Recinto/Categoría Ocupacional',
#     'IP.01': 'Titulación académica',
#     'IP.02': 'Investigaciones realizadas y estatus',
#     'IP.03': 'Publicaciones arbitradas del personal de la UAPA y estatus',
#     'IP.04': 'Producción científica con sello de la UAPA',
#     'IP.05': 'Categoría',
#     'ERS.01': 'Nombre del proyecto',
#     'ERS.02': 'Nombre del proyecto',
#     'ERS.03': 'Tipo de proyecto',
#     'ERS.04': 'Tipo de proyecto',
#     'RS.01': 'Medios sociales y profesional',
#     'RS.02': 'Tipo de informacion publicada',
#     'RS.03': 'Tipo de comentario',
#     'RS.04': 'Categoría',
#     'RS.05': 'Medios sociales y profesional',
#     'RS.06': 'Categoría',
#     'RS.07': 'Instituciones',
#     'IL.01': 'Programas',
#     'IL.02': 'Programas',
#     'IL.03': 'Programas',
#     'PU.01': 'Tipo de espacio',
#     'PU.02': 'Tipo de espacio',
#     'PU.03': 'Tipo de espacio',
# }

GRADO = ['Derecho', 'Ciencia de la Educación, Mención Educación Básica',
         'Ciencia de la Educación, Mención Didáctica de las Lenguas Extranjeras',
         'Ciencia de la Educación, Mención Educación Inicial', 'Ciencia de la Educación, Mención Lengua Española',
         'Ciencia de la Educación, Mención Matemática Física', 'Ciencia de la Educación, Mención Ciencias Sociales',
         'Ciencia de la Educación, Mención Primer Ciclo de la Educación Básica',
         'Ciencia de la Educación, Mención Ciencias de la Naturaleza',
         'Lengua Española y Literatura Orientada a la Educacion Secundaria',
         'Matematica  Orientada a la Educacion Secundaria', 'Ciencias Sociales Orienada a la Educacion Secundaria',
         'Ingles Orientado a la Educacion', 'Educacion Primaria, Primer Ciclo', 'Educación Inicial',
         'Informática Gerencial', 'Ingeniería en Software', 'Lenguas Modernas Mención Turismo',
         'Administración de Empresas', 'Contabilidad Empresarial', 'Mercadeo',
         'Administración de Empresas Turísticas', 'Psicología Clínica', 'Psicología Educativa', 'Psicología',
         'Psicología Industrial', 'Enfermería', 'Periodismo digital', ]

PREGRADO = ['Agrimensura', ]
POSTGRADO = ['Gerencia de Recursos Humanos  - MGH', 'Mercadeo (Postgrado)', 'Gestión de Centros Educativos  - MGC',
             'Historia, con Orientación a la Enseñanza - MAH', 'Informática, con Orientación a la Enseñanza  - EIN',
             'Biología, con Orientación a la Enseñanza ', 'Educación, Mención Lengua Española, Segundo Ciclo ',
             'Lengua Española y Literatura, con Orientación a la Enseñanza  - ELL',
             'Educación, Matemática Física, Segundo Ciclo', 'Matemática, con Orientación a la Enseñanza - EMA',
             'Educación, Mención Historia y Geografía Segundo Ciclo',
             'Especialidad en Habilitación Docente: para Matemática, Nivel Secundario - EHM',
             'Especialidad en Habilitación Docente:  para modalidad Teatro, Nivel Secundario',
             'Especialidad en Habilitación Docente:  para modalidad Artes Plásticas, Nivel Secundario',
             'Especialidad en Habilitación Docente:  para modalidad Educación Musical, Nivel Secundario',
             'Especialidad en Habilitación Docente:  Lenguas Extranjeras (Ingles), para Nivel Secundario',
             'Especialidad en Habilitación Docente:  Lenguas Extranjeras (Frances), para Nivel Secundario',
             'Ciencias de la Educacion, Mencion Gestion de Centros Educativos - EGC',
             'Ciencias de la Educacion, Mencion Gestion de Centros Educativos',
             'Mercadeo, mencion Gerencia de mercadeo - MMG', 'Mercadeo, Mención  Mercadeo Politico',
             'Educación Inicial  - MEI', 'Psicología Clínica  - MPC',
             'Derecho Civil y Procesal Civil Contemporáneos MCP', 'Gerencia de Recursos Humanos',
             'Dirección Financiera - MDF',
             'Legislación de Tierras  - MLT', 'Derecho Penal y Procesal Penal Contemporáneos  - MPP',
             'Gestión de la Tecnología Educativa - MGT', 'Gestion de Instituciones Educativas Virtuales',
             'Derecho Constitucional - MDC', 'Historia, con Orientación a la Enseñanza',
             'Maestría en Terapia Familiar - MTF', 'Innovación y Gestión Empresarial',
             'Dirección y Gestión Tributaria', 'Ciberseguridad - MCS', 'Ciencias de la Educación (Dr.)-DCE']
