# Generated by Django 3.0.10 on 2020-09-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200929_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corte',
            options={'ordering': ['ano']},
        ),
        migrations.RemoveField(
            model_name='corte',
            name='corte_cierre',
        ),
        migrations.RemoveField(
            model_name='corte',
            name='corte_inicio',
        ),
    ]
