# Generated by Django 3.0.10 on 2020-09-29 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200929_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(2000)], verbose_name='Año'),
        ),
    ]
