# Generated by Django 3.0.10 on 2020-12-15 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200929_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(1995)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='periodo',
            field=models.CharField(choices=[('Bimestres', (('b11', 'Bimestre 1-1'), ('b12', 'Bimestre 1-2'), ('b21', 'Bimestre 2-1'), ('b22', 'Bimestre 2-2'), ('b22', 'Bimestre 3-1'), ('b22', 'Bimestre 3-2'))), ('Trimestres', (('t1', 'Trimestre 1'), ('t2', 'Trimestre 2'), ('t3', 'Trimestre 3'), ('t4', 'Trimestre 4'))), ('a', 'Anual'), ('Mensual', (('en', 'Enero'), ('fe', 'Febrero'), ('ma', 'Marzo'), ('ab', 'Abril'), ('may', 'Mayo'), ('ju', 'Junio'), ('jul', 'Julio'), ('ag', 'Agosto'), ('se', 'Septiembre'), ('oc', 'Octubre'), ('no', 'Noviembre'), ('di', 'Diciembre')))], default='b11', max_length=3),
        ),
        migrations.AlterField(
            model_name='segregacion',
            name='indicador',
            field=models.ManyToManyField(limit_choices_to={'componente__visible': True}, related_name='segregacion', related_query_name='segregacion', to='core.Indicador'),
        ),
        migrations.AlterUniqueTogether(
            name='dato',
            unique_together={('segregacion', 'corte', 'indicador')},
        ),
        migrations.AlterUniqueTogether(
            name='segregacion',
            unique_together={('parametro', 'parametro_opcional')},
        ),
    ]
