# Generated by Django 3.0.10 on 2020-12-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201215_2200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segregacion',
            unique_together=set(),
        ),
    ]
