# Generated by Django 3.0.10 on 2020-12-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201216_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segregacion',
            name='parametro',
            field=models.CharField(help_text='Nombre del parámetro para segregar', max_length=100, verbose_name='Parámetro'),
        ),
        migrations.AlterField(
            model_name='segregacion',
            name='parametro_opcional',
            field=models.CharField(blank=True, help_text='Nombre del parámetro opcional para segregar', max_length=100, null=True, verbose_name='Parámetro opcional'),
        ),
    ]
