# Generated by Django 3.0.10 on 2020-12-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201228_0318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dato',
            unique_together=set(),
        ),
    ]
