# Generated by Django 3.0.10 on 2020-12-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201230_0004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dato',
            unique_together={('segregacion', 'corte', 'indicador')},
        ),
    ]
