# Generated by Django 3.0.10 on 2021-02-21 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201230_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='ano',
            field=models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1995)], verbose_name='Año'),
        ),
    ]
