# Generated by Django 3.1.8 on 2021-05-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210221_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='dato',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
    ]
